export enum OrderStatus {
	PENDING = "PENDING",
	WAITING_PAYMENT = "WAITING_PAYMENT",
	PAID = "PAID",
	PROCESSING = "PROCESSING",
	SHIPPED = "SHIPPED",
	DELIVERED = "DELIVERED",
	CANCELLED = "CANCELLED",
}
